# Generated by Django 3.2.18 on 2023-05-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0004_personaldetails_study_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='headings',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='study_icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
