# Generated by Django 3.2.18 on 2023-05-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0005_auto_20230525_0935'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='Skills',
        ),
    ]
