# Generated by Django 3.2.18 on 2023-05-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0011_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headings',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
