# Generated by Django 3.2.18 on 2023-05-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0014_alter_headings_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='..media/project_images/'),
        ),
    ]
