# Generated by Django 3.2.18 on 2023-06-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0016_auto_20230528_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headings',
            name='par1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='headings',
            name='par2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='headings',
            name='par3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='headings',
            name='par4',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
