# Generated by Django 3.2.18 on 2023-06-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0017_auto_20230614_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headings',
            name='par3',
        ),
        migrations.RemoveField(
            model_name='headings',
            name='par4',
        ),
        migrations.AlterField(
            model_name='headings',
            name='big_header',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='headings',
            name='sub_header',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
