# Generated by Django 3.2.18 on 2023-06-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0018_auto_20230617_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headings',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='flag_nationality',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='flag_residency',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
