# Generated by Django 3.2.18 on 2023-06-19 07:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0022_auto_20230619_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='headings',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
