# Generated by Django 3.2.18 on 2023-06-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0023_headings_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='description',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
    ]
