# Generated by Django 3.2.18 on 2023-06-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0024_alter_skills_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='paragraph',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
