# Generated by Django 3.2.18 on 2023-06-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0025_alter_personaldetails_paragraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetails',
            name='paragraph',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='paragraph_1',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='paragraph_2',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='paragraph_3',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='paragraph_4',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='paragraph_5',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
