# Generated by Django 3.2.18 on 2023-06-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0027_project_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='extra_info',
            field=models.CharField(max_length=300),
        ),
    ]
