# Generated by Django 3.2.18 on 2023-06-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0028_alter_project_extra_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills_icon',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
