# Generated by Django 3.2.18 on 2023-06-25 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0029_project_skills_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='skills_icon',
        ),
    ]
