# Generated by Django 3.2.18 on 2023-06-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0030_remove_project_skills_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='extra_info',
            field=models.CharField(max_length=800),
        ),
    ]
