# Generated by Django 3.2.18 on 2023-06-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0031_alter_project_extra_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_site',
            field=models.URLField(default='https://play-some-hangman.herokuapp.com/'),
            preserve_default=False,
        ),
    ]
